"""Add pending_receipt_url to orders

Revision ID: 0108f17ea43c
Revises: 4a13469088ec
Create Date: 2026-02-24 20:09:49.431370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0108f17ea43c'
down_revision: Union[str, Sequence[str], None] = '4a13469088ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('pending_receipt_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pending_receipt_url')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
