"""Add ai_active to customers

Revision ID: 337a16b34da5
Revises: 6d95b4d5b699
Create Date: 2026-05-13 10:32:14.586125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337a16b34da5'
down_revision: Union[str, Sequence[str], None] = '6d95b4d5b699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('ai_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'ai_active')
    # ### end Alembic commands ###
