"""Add address string to Customer

Revision ID: 6d95b4d5b699
Revises: 0108f17ea43c
Create Date: 2026-02-24 20:40:14.846404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d95b4d5b699'
down_revision: Union[str, Sequence[str], None] = '0108f17ea43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
