"""Add inventory config

Revision ID: 7914514b4f3f
Revises: e1f2g3h4i5j6
Create Date: 2026-02-19 11:46:46.456063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7914514b4f3f'
down_revision: Union[str, Sequence[str], None] = 'e1f2g3h4i5j6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('store_addresses', sa.JSON(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('sinpe_number', sa.String(), nullable=True),
    sa.Column('customer_service_phone', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_config_id'), 'inventory_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_config_id'), table_name='inventory_config')
    op.drop_table('inventory_config')
    # ### end Alembic commands ###
