"""Add target animals to products

Revision ID: 891d4227d49e
Revises: 7914514b4f3f
Create Date: 2026-02-19 11:59:27.199206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891d4227d49e'
down_revision: Union[str, Sequence[str], None] = '7914514b4f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('target_animals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'target_animals')
    # ### end Alembic commands ###
