"""add_customer_payment_method

Revision ID: c05cef608ff0
Revises: 4433d2a28840
Create Date: 2026-02-17 13:29:29.374028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05cef608ff0'
down_revision: Union[str, Sequence[str], None] = '4433d2a28840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('default_payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'default_payment_method')
    # ### end Alembic commands ###
